apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: gestionmotpasse
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: gestionmotpasse/backend:latest
          imagePullPolicy: Always # Forcer K8s à chercher la nouvelle image poussée par la CI/CD
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod # Ou le profil Spring configuré pour utiliser PostgreSQL
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres-service:5432/gestionmotpasse_db"
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-password
            - name: JAVA_OPTS
              value: "-Xmx512m"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 15 # Augmenté légèrement pour laisser le temps à Spring de se connecter à Postgres
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 40
            periodSeconds: 30
            failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: gestionmotpasse
spec:
  selector:
    app: backend
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  type: ClusterIP