server.port=8080

# On utilise des variables d'environnement. Si elles n'existent pas, on met une valeur par d�faut apr�s le ":"
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:gestionmotdepasse}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:changeme}
#
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

# Variables pour la s�curit�
app.encryption.key=${ENCRYPTION_KEY:change-me-encryption-key}
app.jwt.secret=${JWT_SECRET:change-me-secret-key}
app.jwt.expiration-ms=86400000