server.port=8080
spring.datasource.url=jdbc:postgresql://localhost:5432/gestionmotdepasse
spring.datasource.username=postgres
spring.datasource.password=ngouye2001
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
app.encryption.key=1234567890123456
app.jwt.secret=change-me-secret-key-please-update
app.jwt.expiration-ms=86400000
